dist: xenial
sudo: required

language: cpp
node_js:
- "8.11.3"
python: 
  - '3.5'

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sudo apt-get install -qq g++-8
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
- git clone https://github.com/emilydolson/Empirical ../Empirical --branch memic_model
- git clone https://github.com/emscripten-core/emsdk.git && cd emsdk && git pull && ./emsdk install latest && ./emsdk activate latest && . ./emsdk_env.sh && cd ..
- pip install --user codecov
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-7
    packages:
      - zlib1g
      - clang-7
      - libclang-7-dev

script:
- make test
- make web-debug
- make web
- make debug
- ./memic_model -TIME_STEPS 5
- make clean
- make
- ./memic_model -TIME_STEPS 5


after_success: 
- git clone https://github.com/emilydolson/force-cover ../force-cover && cd ../force-cover && make force_cover CXX=clang++-7 && cd -
- make coverage CXX=clang++-7
- curl -s https://codecov.io/bash | bash
